export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_REGISTER_SELECTED_STEP = 'SET_REGISTER_SELECTED_STEP';
export const SET_REGISTER_LAST_STEP = 'SET_REGISTER_LAST_STEP';
export const SET_REGISTER_DATA = 'SET_REGISTER_DATA';
export const RESET_REGISTER_DATA = 'RESET_REGISTER_DATA';
export const UPDATE_REGISTER_DATA = 'UPDATE_REGISTER_DATA';
export const SET_COUNTRIES = 'SET_COUNTRIES';

/**
 * Saga initiators.
 */
export const CHECK_SIGNED_IN = 'CHECK_SIGNED_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SET_CUSTOMER_EXTRA = 'SET_CUSTOMER_EXTRA';
export const GET_CUSTOMER_INFO = 'GET_CUSTOMER_INFO';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const ACCEPT_AGREEMENT = 'ACCEPT_AGREEMENT';
export const SEND_OTP = 'SEND_OTP';
export const CHECK_OTP = 'CHECK_OTP';
